# Generated by Django 4.1.3 on 2023-06-29 19:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0003_remove_order_uuid_order_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='id',
            new_name='orderid',
        ),
    ]
